version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-server
    container_name: fast-container
    command: python main.py
    ports:
      - "8000:8000"
    networks:
      - fast-network
    volumes:
      - ./:/usr/src/app/
  
  nginx:
    container_name: fast-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - app
    networks:
      - fast-network

networks:
    fast-network:
        driver: bridge