version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi-server
    container_name: fast-container
    command: python main.py
    ports:
      - "8000:8000"
    networks:
      - fast-network
    volumes:
      - ./:/usr/src/app/
  
  nginx:
    container_name: fast-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - app
    networks:
      - fast-network

  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: app-client
    container_name: app-vue-client
    command: npm run dev
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - app
    ports:
      - "8080:8080"
    networks:
      - fast-network

networks:
    fast-network:
        driver: bridge